# Generated by Django 4.2.23 on 2025-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_id', models.CharField(max_length=50)),
                ('gps_lat', models.FloatField()),
                ('gps_long', models.FloatField()),
                ('speed', models.FloatField()),
                ('engine_temp', models.FloatField()),
                ('fuel_level', models.FloatField()),
                ('tire_pressure', models.FloatField()),
            ],
        ),
    ]
